# Lambda Function

In [ ]:
somadosquadrados = lambda a,b: a**3 - b**2 

In [ ]:
somadosquadrados(2,3)

In [6]:
somadosquadrados(3,2)

23

In [7]:
f = lambda x: x**2

In [8]:
f(9)

81

In [17]:
kmh = [40, 50, 56, 64, 73, 79, 85, 96,100,120]

In [18]:
mph = []
for i in kmh:
    mph.append(i/1.61)
print(mph)

[24.844720496894407, 31.05590062111801, 34.78260869565217, 39.75155279503105, 45.3416149068323, 49.06832298136646, 52.795031055900616, 59.62732919254658, 62.11180124223602, 74.53416149068323]


In [22]:
mph2 = list(map(lambda x: x/1.61, kmh))
print(mph2)

[24.844720496894407, 31.05590062111801, 34.78260869565217, 39.75155279503105, 45.3416149068323, 49.06832298136646, 52.795031055900616, 59.62732919254658, 62.11180124223602, 74.53416149068323]


# List comprehation

In [24]:
mph3 = [i/1.61 for i in kmh]
print(mph3)

[24.844720496894407, 31.05590062111801, 34.78260869565217, 39.75155279503105, 45.3416149068323, 49.06832298136646, 52.795031055900616, 59.62732919254658, 62.11180124223602, 74.53416149068323]


## NumPy Use

In [27]:
import numpy as np

In [28]:
a = np.array([1,2,3])

In [34]:
a

array([1, 2, 3])

In [33]:
b = np. array([(2,5,7), (5,3,9),(3,2,1)])
print(b)

[[2 5 7]
 [5 3 9]
 [3 2 1]]


In [39]:
c = np.zeros((4,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
y = np.eye(10)
print(y)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [42]:
b.max()

9

In [45]:
b.mean()

4.111111111111111

In [46]:
y.sum()

10.0

# Pandas

In [49]:
import pandas as pd

In [51]:
dados2 = pd.read_csv('athlete_events.csv')

In [52]:
dados2.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN